TurkeydeMacBook-Pro:imagenet18 turkey$ python train.py --machines=1
2018-10-11 14:32:36.305227 0.imagenet: Using account 318581613021, region us-east-1, zone 
('Resources already created, no-op',) {}
('Choosing placement_group for run imagenet-1',) {}
('Creating threads',) {}
('Using account 318581613021, region us-east-1, zone ',) {}
('Resources already created, no-op',) {}
2018-10-11 14:32:38.797860 0.imagenet: Using image pytorch.imagenet.source.v7
2018-10-11 14:32:42.122245 0.imagenet: Reusing ec2.Instance(id='i-09466a3b78ec20a62')
ssh -i /Users/turkey/.ncluster/ncluster-turkey-318581613021-us-east-1.pem ubuntu@18.207.250.206
2018-10-11 14:32:42.812646 0.imagenet: Setting up tmux
2018-10-11 14:32:43.390808 0.imagenet: Checking for initialization status
2018-10-11 14:32:43.390906 0.imagenet: downloading is_initialized
2018-10-11 14:32:43.577301 0.imagenet: running install script
2018-10-11 14:32:43.577395 0.imagenet: Mounting EFS
Exception are  [KeyError('ncluster',)]
Traceback (most recent call last):
  File "train.py", line 199, in <module>
    main()
  File "train.py", line 166, in main
    install_script=open('setup.sh').read())
  File "/Users/turkey/anaconda3/lib/python3.6/site-packages/ncluster/ncluster.py", line 106, in make_job
    install_script=install_script, **kwargs)
  File "/Users/turkey/anaconda3/lib/python3.6/site-packages/ncluster/aws_backend.py", line 873, in make_job
    raise exceptions[0]
  File "/Users/turkey/anaconda3/lib/python3.6/site-packages/ncluster/aws_backend.py", line 859, in make_task_fn
    **kwargs)
  File "/Users/turkey/anaconda3/lib/python3.6/site-packages/ncluster/aws_backend.py", line 803, in make_task
    instance_type=instance_type)
  File "/Users/turkey/anaconda3/lib/python3.6/site-packages/ncluster/aws_backend.py", line 109, in __init__
    self._mount_efs()
  File "/Users/turkey/anaconda3/lib/python3.6/site-packages/ncluster/aws_backend.py", line 163, in _mount_efs
    efs_id = u.get_efs_dict()[u.get_prefix()]
KeyError: 'ncluster'